#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9631FEAF0CC6227 (infra-root@openstack.org)
#
Name     : os-testr
Version  : 0.8.0
Release  : 22
URL      : http://tarballs.openstack.org/os-testr/os-testr-0.8.0.tar.gz
Source0  : http://tarballs.openstack.org/os-testr/os-testr-0.8.0.tar.gz
Source99 : http://tarballs.openstack.org/os-testr/os-testr-0.8.0.tar.gz.asc
Summary  : A testr wrapper to provide functionality for OpenStack projects
Group    : Development/Tools
License  : Apache-2.0
Requires: os-testr-bin
Requires: os-testr-python
Requires: Babel
Requires: pbr
Requires: python-subunit
Requires: testrepository
Requires: testtools
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
========
os-testr
========
.. image:: https://img.shields.io/pypi/v/os-testr.svg
:target: https://pypi.python.org/pypi/os-testr/
:alt: Latest Version

%package bin
Summary: bin components for the os-testr package.
Group: Binaries

%description bin
bin components for the os-testr package.


%package python
Summary: python components for the os-testr package.
Group: Default

%description python
python components for the os-testr package.


%prep
%setup -q -n os-testr-0.8.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489852887
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489852887
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/generate-subunit
/usr/bin/ostestr
/usr/bin/subunit-trace
/usr/bin/subunit2html

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
