#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xFC43F0EE211DFED8 (infra-root@openstack.org)
#
Name     : os-testr
Version  : 1.1.0
Release  : 34
URL      : http://tarballs.openstack.org/os-testr/os-testr-1.1.0.tar.gz
Source0  : http://tarballs.openstack.org/os-testr/os-testr-1.1.0.tar.gz
Source1  : http://tarballs.openstack.org/os-testr/os-testr-1.1.0.tar.gz.asc
Summary  : A testr wrapper to provide functionality for OpenStack projects
Group    : Development/Tools
License  : Apache-2.0
Requires: os-testr-bin = %{version}-%{release}
Requires: os-testr-license = %{version}-%{release}
Requires: os-testr-python = %{version}-%{release}
Requires: os-testr-python3 = %{version}-%{release}
Requires: pbr
Requires: python-subunit
Requires: stestr
Requires: testtools
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : python-subunit
BuildRequires : stestr
BuildRequires : testtools

%description
========
os-testr
========

.. image:: https://img.shields.io/pypi/v/os-testr.svg
    :target: https://pypi.org/project/os-testr/
    :alt: Latest Version

.. image:: https://img.shields.io/pypi/dm/os-testr.svg
    :target: https://pypi.org/project/os-testr/
    :alt: Downloads

A testr wrapper to provide functionality for OpenStack projects.

* Free software: Apache license
* Documentation: https://docs.openstack.org/os-testr/
* Source: https://opendev.org/openstack/os-testr
* Bugs: https://bugs.launchpad.net/os-testr

Features
--------

.. warning::
   ``ostestr`` command is deprecated. Use `stestr`_ command instead like
   following

   0. Install `stestr`_ (This step is already done if you're using ostestr.)
   1. You can use ``stestr run ...`` instead of ``ostestr ...``
   2. You can use ``stestr list ...`` instead of ``ostestr --list ...``

   For more sub commands and options, please refer to `stestr help` or the
   `stestr`_ document.

* ``ostestr``: a testr wrapper that uses subunit-trace for output and builds
  some helpful extra functionality around testr
* ``subunit-trace``: an output filter for a subunit stream which provides
  useful information about the run
* ``subunit2html``: generates a test results html page from a subunit stream
* ``generate-subunit``: generate a subunit stream for a single test

.. _stestr: https://stestr.readthedocs.io/

%package bin
Summary: bin components for the os-testr package.
Group: Binaries
Requires: os-testr-license = %{version}-%{release}

%description bin
bin components for the os-testr package.


%package license
Summary: license components for the os-testr package.
Group: Default

%description license
license components for the os-testr package.


%package python
Summary: python components for the os-testr package.
Group: Default
Requires: os-testr-python3 = %{version}-%{release}

%description python
python components for the os-testr package.


%package python3
Summary: python3 components for the os-testr package.
Group: Default
Requires: python3-core
Provides: pypi(os-testr)

%description python3
python3 components for the os-testr package.


%prep
%setup -q -n os-testr-1.1.0
cd %{_builddir}/os-testr-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583195676
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/os-testr
cp %{_builddir}/os-testr-1.1.0/LICENSE %{buildroot}/usr/share/package-licenses/os-testr/294b43b2cec9919063be1a3b49e8722648424779
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/generate-subunit
/usr/bin/ostestr
/usr/bin/subunit-trace
/usr/bin/subunit2html

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/os-testr/294b43b2cec9919063be1a3b49e8722648424779

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
